# Generated by Django 4.2.4 on 2023-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(upload_to="goods/images/"),
        ),
    ]
