# Generated by Django 4.2.4 on 2023-09-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0002_alter_picture_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="picture",
            field=models.ImageField(upload_to="goods/images"),
        ),
        migrations.DeleteModel(
            name="Picture",
        ),
    ]
