# Generated by Django 4.2.4 on 2023-09-07 09:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0003_alter_goods_picture_delete_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date_time_actual", models.DateTimeField(auto_now=True)),
                (
                    "good_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goods.goods"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("paid", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("good_id", models.ManyToManyField(blank=True, to="goods.goods")),
                ("price_id", models.ManyToManyField(blank=True, to="goods.price")),
            ],
        ),
    ]
