# Generated by Django 4.2.4 on 2023-09-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0006_remove_order_price_goods_current_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price_id",
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="order",
            name="good_id",
        ),
        migrations.AddField(
            model_name="order",
            name="good_id",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.PROTECT, to="goods.goods"
            ),
            preserve_default=False,
        ),
    ]
