# Generated by Django 4.2.4 on 2023-09-09 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0007_remove_order_price_id_order_price_alter_order_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="price_id",
            field=models.ManyToManyField(blank=True, to="goods.price"),
        ),
        migrations.AlterField(
            model_name="order",
            name="count",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.RemoveField(
            model_name="order",
            name="good_id",
        ),
        migrations.AddField(
            model_name="order",
            name="good_id",
            field=models.ManyToManyField(blank=True, to="goods.goods"),
        ),
    ]
