# Generated by Django 4.2.4 on 2023-09-21 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0010_favoritesstatuses_goods_courses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goods",
            old_name="courses",
            new_name="favorites_statuses",
        ),
    ]
