# Generated by Django 4.2.4 on 2023-09-21 11:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0011_rename_courses_goods_favorites_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="favorites_statuses",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="goods.FavoritesStatuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
