# Generated by Django 4.2.4 on 2023-09-21 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0012_alter_goods_favorites_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="favorites_statuses",
            field=models.ManyToManyField(
                blank=True,
                through="goods.FavoritesStatuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CompareStatuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="goods.goods"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="goods",
            name="compare_statuses",
            field=models.ManyToManyField(
                blank=True,
                related_name="compare_goods_set",
                through="goods.CompareStatuses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
