# Generated by Django 4.2.4 on 2023-09-21 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("goods", "0013_alter_goods_favorites_statuses_comparestatuses_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goods",
            name="ordered",
            field=models.ManyToManyField(
                blank=True,
                related_name="orders_set",
                through="goods.Order",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
