# Generated by Django 4.2.4 on 2023-09-23 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0014_goods_ordered"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "is_active",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                (
                    "size_in_percent",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("for_each_numbers", models.IntegerField(blank=True, null=True)),
                ("min_order_sum", models.IntegerField(blank=True, null=True)),
                (
                    "for_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goodscategories",
                    ),
                ),
                (
                    "for_goods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.goods",
                    ),
                ),
            ],
        ),
    ]
