# Generated by Django 4.2.4 on 2023-09-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0015_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="is_for_every",
            field=models.BooleanField(default=False),
        ),
    ]
